# Generated by Django 5.2.17 on 2026-09-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
