# Generated by Django 5.2.17 on 2026-09-09 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
