# Generated by Django 5.2.17 on 2026-09-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='thumbnailUrl',
            new_name='thumbnail_url',
        ),
    ]
