# Generated by Django 5.2.17 on 2026-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_rename_thumbnailurl_photo_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/'),
        ),
    ]
