# Generated by Django 5.2.17 on 2026-09-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_migrate_user_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
