# Generated by Django 5.2.17 on 2026-09-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_ccompany_user_location_user_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ccompany',
            new_name='company',
        ),
    ]
